= CalConnect Standard: Guidelines against calendar abuse for calendaring and mail system operators
:title: Guidelines against calendar abuse for calendaring and mail system operators
:docnumber: CD 18XX
:status: working-draft
:doctype: standard
:edition: 1
:copyright-year: 2018
:revdate: 2018-05-16T00:00:00Z
:language: en
:technical-committee: CALSPAM
:draft:
:toc:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is global non-profit
organization with the aim to facilitate interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives and in this case also aligned
with the procedures used at M3AAWG.

In particular the different approval criteria needed for the different types of
CalConnect documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives and M3AAWG.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.


:sectnums!:
== Introduction

=== Definition

"Calendar spam", unsolicited calendar events and meeting invitations, is a recently
exploited channel inserting unsolicited or otherwise unwanted events and invitations into
calendaring & scheduling systems. It is a new form of application-specific spam which
takes advantage of the application layer across multiple technologies that spans
scheduling, calendaring and messaging systems.
As is the case with email spam, calendar spam is not only used to deliver unwanted
information, but can also be used for malicious purposes such as phishing attempts
and delivering dangerous payloads.

As calendar events and meeting invitations are often transported and delivered via
email, combatting calendar spam requires awareness, intervention and integration
with email systems and services.

=== Impact

Calendar spam is unique in a number of ways:

. Calendar spam, unlike email, can be placed chronologically anywhere in calendars, in
the past or the future, not just the present, making it difficult detect at the time of
delivery.

. Spam meeting invitations, may automatically see these unwanted invitations added to
their calendar without their consent, with notifications sent to all their devices.
These invitations are not only difficult to find, but in some cases there is no way for
the user to remove these events short of deleting the entire calendar.

. Calendar events and meeting invitations do not yet carry the rich provenance (detailed
header information) which today accompanies email, making it difficult to ascertain,
where and when events originated and were delivered.

. Calendar events often contain notifications/alarms which are often propagated across
a users many desktop and mobile calendaring clients.

:sectnums:
== Scope

This document specifies guidelines for calendaring and mail system operators to:

* detect the occurrence of calendar abuse;

* processes and procedures to mitigate calendar abuse; and

* definition of acceptable practices with calendar usage.


[bibliography]
== Normative References

The following documents are referred to in the text in such a way that some or
all of their content constitutes requirements of this document. For dated
references, only the edition cited applies. For undated references, the latest
edition of the referenced document (including any amendments) applies.

// Insert references here:
* [[[iMIP,IETF RFC 6047]]], _iCalendar Message-Based Interoperability Protocol (iMIP)_
* [[[iTIP,IETF RFC 5546]]], _iCalendar Transport-Independent Interoperability Protocol (iTIP)_


== Terms, definitions and abbreviations

=== Terms and definitions

For the purposes of this document, the following terms and definitions apply.


[[calendar-system]]
==== calendar system

an information system, that provides the calendar and scheduling functionality for their
user accounts. This includes creating, editing and deleting events as well as scheduling
events between different user accounts including user accounts from other calendaring
systems.

The _calendar system_ should apply state-of-the-art methods to prevent spam being send and
received for user accounts on their system.

NOTE: The term _calendar system_ in this standard specifically refers
to calendaring systems that fulfill the requirements of CalConnect
calendaring standards.

[[calendar-spam]]
==== calendar spam

unsolicited calendar events and meeting invitations delivered through calendaring systems

[[calendar-abuse]]
==== calendar abuse

malicious usage of a _calendar system_ (<<calendar-system>>),
possibly leading to an _attack_ (<<ISO27000,clause 3.2>>)
on the receiving user

[[attack]]
==== attack

attempt to destroy, expose, alter, disable, steal or gain unauthorized
access to or make unauthorized use of an asset

[.source]
<<ISO27000>>


[[mail-system]]
==== mail system

an information system that provides mail functionality. The most used method to send
calendar invites between users is _iMIP_ (<<iMIP>>), a way of exchanging iTIP (<<iTIP>>) messages
using email. Therefor _mail systems_ play a vital role in connecting users from different
providers by creating events and inviting other users to join. Mail systems are used to
transport the calendar relevant information from organizers to attendees of events.

The _mail system_ should apply state-of-the-art methods to prevent spam being send and
received for user accounts on their system.

[[user-system]]
==== user system

an information system that provides authentication and autorisation functionality. The
_user system_ should prevent fake, bot or spam registrations in order to limit the
number of user accounts on their system, that can later be used for creating spam
(either mail or calendar).

The _user system_ should also prevent real user accounts being compromised by
malicious actors by providing state-of-the-art authentication methods e.g. two-factor-
authentication.

[[spam]]
==== spam

unsolicited information


[[abbrev]]
=== Abbreviations

For the purposes of this document, the following abbreviations apply.

[[terms-imip]]
==== iMIP

iCalendar Message-Based Interoperability Protocol (iMIP)

[.source]
<<iMIP>>

[[terms-itip]]
==== iTIP

iCalendar Transport-Independent Interoperability Protocol (iTIP)

[.source]
<<iTIP>>

[[terms-smtp]]
==== SMTP

Simple Mail Transfer Protocol

[.source]
<<SMTP>>



== Best common practices for mitigating ways calendar spam occurs

=== Detecting and mitigating spam on source system

User accounts could be compromised by malicious actors or free hosting providers could
be abused with bots signing up for free accounts. These accounts are then used to create
calendar spam events. The calendar system uses templating to send an email invitation
with the calendar event attached and the event content will also be inserted into body
of the email.  The "source" hosting provider should take steps to detect and mitigate this
internal abuse on the calendar system and the email system.

==== using calendar systems

There are different best common practices that can be applied here:

. abuse detection on frontend usage using input as network/IPs, user agents, click rate /
path

. checking the event content (subject, description, recurrence, number of attendees,
links, ...) for typical spam pattern before creating the event and sending the email
invitations

with possible actions if potential spam is detected e.g. not sending, display frontend
error or feedback, alert user account, apply rate limiting, demand solving captcha before
sending and more.

==== using smtp

There are different best common practices that can be applied here:

. abuse detection for SMTP access using input as network, DNSBL, ...

. check email for spam pattern (malicious content, blacklisted/known phishing URLs, ...)
using standard email anti-spam scanning applications

with possible actions if potential spam is detected e.g. not sending, using specific
black mailer for sending indicating receivers about potential spam content and more.


=== detecting and mitigating spam on receiving system

Spam events are typically received by recipients in two ways:

. via email from an external system, or

. directly from another account (bot or compromised) within the _calendar system_

Events from internal accounts may propagate natively within the _calendar system_ or they
may propagate over email, depending on implementation.  The "receiving" hosting provider
can take steps to detect and mitigate the "external" abuse on the _calendar system_ and
the _mail system_.

==== mail system

There are different best common practices that can be applied here:

. abuse detection for receiving email including input as network, mail header/
structure, ...

. check email for spam pattern using standard email anti-spam scanning applications,
DNSBLs, URIBLs, etc.

. check sender From address reputation using internal and external sources e.g. subscribe
to InfoSec feeds of known malicious addresses, organiser on white list, ...

with possible actions if potential spam detected e.g. not accepting (reject or discard),
putting in quarantaine or spam folder. As some of these actions do not deliver the email
to the user and no interaction with the _calendar system_ occurs, the recipient
has no way to handle false positives. Therefor these actions can only be taken if the
_mail system_ is very certain about this being abuse or spam. For these events also the
interaction with the _calendar system_ should not be initiated.

For some of the milder action e.g. putting in spam folder, the user should be offered
options, that allow these emails to be marked as false positives and offer manual insert
into calendar option in app/web app/...

==== interaction between _mail system_ and _calendar system_

When interacting between _mail system_ and _calendar system_ the following best common
practices should be applied:

. the interaction should only be triggered for emails not already identified as spam
during applying the above mentioned best common practices for mail systems 

. the events should be parsed on _calendar system_ side as the domain knowledge about
how events are structured is there (and not in the _mail system_)

. the event content should be checked for spam pattern (subject, description, recurrence,
links, ...) to determine the likeliness being _spam_

. depending on the likeliness being _spam_, rules should be applied offered in the
users settings for insert (e.g. only automatic insert for organizers on a white
list/personal address book, state of this events in availability of calendar (e.g. free,
conditional or blocked))

with possible actions if potential spam detected e.g. not automatically inserting,
deactivated notifications, ...

==== _calendar system_

Besides inserting or not inserting the received events into the user calendar
during the interaction between _mail system_ and _calendar system_, the _calendar
system_ should offer these best common practices:

. offer delete option for unwanted events e.g. mark as spam in app/web app/... in order
to give the user the option for deleting the unwanted event without notifying the
organizer. Does ARF need to be extended for calendar abuse reporting?

. store information about how an event was inserted into the users calendar e.g. Mail ID
in order to be able to inform the user about this and prevent extended information for
being able to inform the sending system about the abuse

with possible actions if spam is detected by the user e.g. sending Feedback loop if
MailID and original email is still available in the _mail system_.

=== other ways calendar _spam_ can occur

==== subscribing to shared calendars containing malicious events

Another way how malicious events can end up in users calendar are shared calendars
being manipulated on origin side. Popular calendars e.g. official vacation/bank holidays
in countries or states or schedules of populat sports clubs could be target for phishing
/ taken over by spammers.

Single malicious events within these subscribed calendars can not be deleted if shared
read-only. More robust controls may be needed for calendar subscribers, but unsubscribing
the specific calendar can solve the problem on an all or nothing approach (also the
wanted events are then unsubscribed and deleted from users calendar).

==== _iTIP_

Calendar systems using _iTIP_ for direct communication between each other e.g. within
the same _calendar system_ also need to consider and implement anti-abuse options as
mentioned above.

== Conclusion

TODO.



[[AnnexA]]
[appendix,obligation=informative]
== Technical information

=== Structure of an best practice iMIP message containing an event

Email messages may have more than a single iCalendar file attached, but the best practice
is to only attach a single iMIP (<<iMIP>>) file to each email.

The recommended structure the email is as follows:

[source,json]
----
 multipart/mixed
    multipart/alternative
        text/plain
        text/html
    text/calendar; method=REQUEST
    application/ics (with a content-disposition:attachment) BASE64
----

This structure is based on interoperability testing with various existing implementations.
Some clients will only see the part with the standard `text/calendar` content-type and the
method header. Other clients are only able to attached parts with `application/ics` (which
is non-standard).

It is also recommended that the filename of the `application/ics` part ends
with the `.ics` file extension.

Some vendors add links within the HTML part which can be used from non-calendaring-aware
email clients to accept or decline a request without having to process the calendar parts
at all. The server just updates the ORGANIZER’s copy of the event based on the link
clicked.

When using standard conform _calendar systems_ the structure of the email will be like
above and the `text/plain` and `text/html` part of the message in the body will also include
information of the event e.g. subject, description, ... . This does not prevent spammers
from not including this potential malicious content besides the attached files, so all
parts need to be parsed to detect malicious content in events.

[bibliography]
== Bibliography

* [[[ISO27000,ISO/IEC 27000:2018]]], _Information technology -- Security techniques -- Information security management systems -- Overview and vocabulary_ https://www.iso.org/standard/73906.html
* [[[SMTP,IETF RFC 2821]]], _Simple Mail Transfer Protocol (SMTP)_ https://tools.ietf.org/html/rfc2821

