= CalConnect Standard: Calendar operator practices -- Guidelines to protect against calendar abuse
:title: Calendar operator practices -- Guidelines to protect against calendar abuse
:docnumber: 18003
:status: draft-standard
:doctype: report
:edition: 1
:copyright-year: 2018
:revdate: 2018-10-28T00:00:00Z
:language: en
:technical-committee: CALSPAM
:draft:
:toc:

.Foreword
The Calendaring and Scheduling Consortium ("`CalConnect`") is global non-profit
organization with the aim of facilitating interoperability of technologies across
user-centric systems and applications.

CalConnect works closely with liaison partners including international
organizations such as ISO, OASIS and M3AAWG.

The procedures used to develop this document and those intended for its further
maintenance are described in the CalConnect Directives, and in this case, also aligned
with the procedures used at M3AAWG.

In particular the different approval criteria needed for the different types of
CalConnect documents should be noted. This document was drafted in accordance with the
editorial rules of the CalConnect Directives.

Attention is drawn to the possibility that some of the elements of this
document may be the subject of patent rights. CalConnect shall not be held responsible
for identifying any or all such patent rights. Details of any patent rights
identified during the development of the document will be in the Introduction
and/or on the CalConnect list of patent declarations received (see
www.calconnect.com/patents).

Any trade name used in this document is information given for the convenience
of users and does not constitute an endorsement.

This document was prepared by Technical Committee _{technical-committee}_.


:sectnums!:
== Introduction

=== Rise of calendar spam

"`Calendar spam`", unsolicited or otherwise unwanted calendar events and meeting invitations,
is a recently exploited channel for abuse aimed at users of
calendaring & scheduling systems.

It is a new form of application-specific spam which
takes advantage of the application layer across multiple technologies that spans
scheduling, calendaring and messaging systems.
As is the case with email spam, calendar spam is not only used to deliver unwanted
information, but can also be used for malicious purposes such as phishing attempts
and delivering dangerous payloads.

As calendar events and meeting invitations are often (but not exclusively) transported and
delivered via email, combatting calendar spam requires awareness, intervention and
integration with email systems and services.


=== Impact of calendar spam

Calendar spam is unique in a number of ways:

. Calendar spam, unlike email, can be placed chronologically anywhere in calendars, in
the past or the future, not just the present, making it difficult for the end-user to
detect at the time of delivery.

. Spam meeting invitations, may automatically see these unwanted invitations added to
their calendar without their consent, with notifications sent to all their devices.
These invitations are not only difficult to find, but in some cases there is no way for
the user to remove these events short of deleting the entire calendar.

. Calendar events and meeting invitations do not yet carry the rich provenance which today
accompanies email (detailed header information), making it difficult to ascertain
where and when events originated and were delivered.

. Calendar events often contain notifications/alarms which are propagated across
a user's desktop and mobile calendaring clients. It is common for users to have multiple
calendaring clients which exacerbates the abuse.

. Calendar events can include recurrence meaning that one event can show up in the user's
calendar multiple times with multiple notifications/alarms being triggered over time.


:sectnums:
== Scope

This document specifies guidelines for calendar and mail system operators to:

* detect the occurrence of calendar abuse;

* consider processes and procedures to mitigate calendar abuse; and

* suggest acceptable (non-abusive) practices with calendar usage.



[bibliography]
== Normative references

// Insert references here:
* [[[iMIP,IETF RFC 6047]]], _iCalendar Message-Based Interoperability Protocol (iMIP)_

* [[[iTIP,IETF RFC 5546]]], _iCalendar Transport-Independent Interoperability Protocol (iTIP)_


[[terms]]
== Terms, definitions and abbreviations

=== Terms and definitions

[[calendar-spam]]
==== calendar spam

calendar events and meeting invitations containing _spam_ (<<term-spam>>) delivered through _calendar systems_ (<<term-calendar-system>>)


[[term-calendar-abuse]]
==== calendar abuse

malicious usage of a _calendar system_ (<<term-calendar-system>>),
possibly leading to an _attack_ (<<ISO27000,clause 3.2>>)
on the receiving user


[[term-spam]]
==== spam

unsolicited or unwanted information


[[attack]]
==== attack

attempt to destroy, expose, alter, disable, steal or gain unauthorized
access to or make unauthorized use of an asset

[.source]
<<ISO27000>>


[[term-calendar-system]]
==== calendar system

information system that provides calendar and scheduling functionality for user
accounts


[[mail-system]]
==== mail system

information system that provides electronic mail functionality


[[user-system]]
==== user system

information system that provides authentication and authorization functionality



[[abbrev]]
=== Abbreviations

iMIP:: iCalendar Message-Based Interoperability Protocol (see <<iMIP>>)

iTIP:: iCalendar Transport-Independent Interoperability Protocol (see <<iTIP>>)

SMTP:: Simple Mail Transfer Protocol (see <<SMTP>>)

DNSBL:: Domain Name System-based Blackhole List

URIBL:: Realtime URI Blacklist

////
Calendar system

This includes creating, editing and deleting events as well as scheduling
events between different user accounts including user accounts from other calendaring
systems.

The _calendar system_ should apply state-of-the-art methods to prevent spam being sent
from and received by user accounts on their system.
////

////
NOTE: _calendar system_ in this document specifically refers
to calendaring systems that fulfill the requirements of CalConnect
calendaring standards.
////


////
Mail system

NOTE: The most used method to send calendar invites between users is _iMIP_ (<<iMIP>>), a way of exchanging iTIP (<<iTIP>>)
messages using email. Therefor _mail systems_ play a vital role in connecting users from
different providers by creating events and inviting other users to join. Mail systems are
used to transport the calendar relevant information from organizers to attendees of events.

The _mail system_ should apply state-of-the-art methods to prevent spam being sent by and
received from user accounts on their system.
////


////

User system

. The
_user system_ should prevent fake, bot or spam registrations in order to limit the
number of user accounts on their system, that can later be used for creating spam
(either mail or calendar).

The _user system_ should also prevent real user accounts being compromised by
malicious actors by providing state-of-the-art authentication methods e.g. two-factor-
authentication.
////


== Calendar spam and its delivery path

Calendar spam and calendar abuse originates at the OSI application layer
but also travels across multiple application layer technologies
through networked hosts.

Best practices used at the various checkpoints
that a calendar spam instance encounters within its delivery path
are described in clauses that follow.


== Mitigating calendar abuse at source

=== General

Calendar spam may be produced by innocent calendar systems when:

* its users were compromised;
* it contains abusive users (such as a free-of-charge hosting provider).

In the latter case, approaches such as automation ("`bots`") can exacerbate
the issue with the automated creation of free accounts.

Such user accounts can be readily used to create calendar spam events:

. The malicious user account inserts spam content into a newly created calendar event;
. The calendar system uses templating to send an email invitation with the calendar event attached;
. The event content, which contains spam, will be inserted into body of the email.

The "`source`" calendar system provider should take steps to detect and
mitigate such internal abuse, by placing detection mechanisms and
automated responses at its calendar system and its email system associated
with calendar event delivery.


=== Source calendar system

The source calendar system is where an calendar abuse instance originates from.

The source calendar system can apply the following best practices:

. abuse detection should be performed, through channels such as:

.. user interface and input detection, such as user agent checks;
.. network origination, such as network addresses and IPs; and
.. user behavior such as click rate.

. detection of malicious content for typical spam patterns,
  before event creation and the subsequent sending of email invitations,
  by checking event content, such as:

.. subject;
.. description;
.. recurrence;
.. number of attendees; and
.. links.


A number of potential actions can be invoked once potential spam
is detected, such as:

. deny the sending of the calendar invite;
. display of errors and feedback at the user interface;
. alert the owner of the user account in case the user account has been hijacked;
. application of rate limiting to prevent automated spamming;
. implement automation detection measures, such as usage of a CAPTCHA prior to sending an invitation; and
. blocking the user account altogether.


=== Electronic mail system (SMTP)

The source electronic mail system is where the calendar system delivers
an event invitation to for its forwarding.

The following mitigation measures should be taken at the electronic mail system:

. abuse detection for SMTP access should be performed based on input, such as:

.. network patterns of the originator;
.. DNSBL checks against the originating IP.

. detection of spam content patterns of the email message, using standard email anti-spam scanning applications:

.. scanning for malicious content;
.. detection of blacklisted and/or known phishing URLs.


A number of potential actions can be invoked once potential spam
is detected, such as:

. bounce the email that contains suspected calendar spam;
. silently discard the email with suspected calendar spam;
. communicate with the upstream calendar provider to indicate potential abuse; and
. communicate with downstream email providers who will be receive the potential spam.


== Mitigating calendar abuse at destination

=== General

Calendar spam events are typically received by recipients in two ways:

. via email from an external email system; or

. directly from another account within the same calendar system the recipient resides on. +
+
NOTE: The case of a same-system account abuse can apply when the calendar system
contains compromised accounts.


Calendar spam events originating from a calendar system may be propagated
back to its own accounts through different channels, depending on their method of integration,
such as:

* from within the calendar system, where the event did not leave the calendar system; or

* delivered through email, where the event was sent by the calendar system
to an internal email system, and re-routed back to the originating calendar system.

System providers at the receiving end
should therefore take steps to detect and mitigate abuse originating
from both external and internal calendar and mail systems.


=== Electronic mail system

The following best practices apply:

. abuse detection for receiving email by analyzing input, such as:

.. originating network addresses;
.. content of the mail header and its structure.

. analysis of email spam content patterns using standard email anti-spam scanning
applications, such as through:

.. checking of DNSBLs; and
.. checking of URIBLs.

. checking email header content against internal and external sources, such as:

.. verification of sender address reputation using the `From:` address;

.. detection of known malicious addresses from security advisories;

.. determining whether the organizer has been whitelisted.


Actions to be taken when potential spam is detected are provided below:

. bounce the message;
. silently discard the message;
. pick out the message into quarantaine;
. moving the message into the spam folder.

When potential spam is detected, "`interaction`" (e.g. adding the event to the end-user's calendar) between the recipient and the sender at the calendar system shall not proceed.

Certain mitigation actions, such as the silent discard of an email,
do not provide any feedback to the originating calendar system. This means
that there will be no method for the originator of the calendar event
to learn of these events and handle them in the case of false positives.

Therefore, these actions should only be taken if the
electronic mail system is very certain about the calendar invitation
being an abuse instance or spam.

For some of the milder actions (e.g. putting in spam folder),
the calendar system should provide options to the recipient user. For example, the recipient user can mark such emails as false positives, and are able to manually insert them into the user's calendar.


// TODO: RT review

==== Interactions between the calendar system and the mail system

Interaction between the electronic mail system and the calendar system should follow these best
common practices:

. the interaction should only be triggered for emails not already identified as spam
during applying the above mentioned best common practices for mail systems

. the events should be parsed by the _calendar system_ due to the domain knowledge
regarding calendar structure not present or mature in most types of _mail system_

. the event content should be checked for spam patterns (subject, description, recurrence,
links, ...) to determine the likeliness being _spam_

. depending on the likeliness being _spam_, spam handling options should be offered in the
users settings for insert (e.g. only automatic insert for organizers on a whitelist /
personal address book, state of this event in availability of calendar (e.g. free,
conditional or blocked))

There are many potential actions that could be invoked if potential spam detected )e.g.
not automatically inserting, deactivated notifications, ...)

==== _calendar system_

Besides inserting or not inserting the received events into the user calendar
during the interaction between _mail system_ and _calendar system_, the _calendar
system_ should offer these best common practices:

. offer the end-user a delete option for unwanted events (e.g. mark as spam in the client)
in order to give the user the option for deleting the unwanted events without notifying
the organizer.

. consider sending ARF reports for calendar abuse reporting

. store information about how an event was inserted into the users calendar (e.g.
Message-ID) in order to be able to inform the user about this contextual information and
to provide additional information to the sending system about the abuse

There are many potential actions that could be invoked if spam is detected by the user
e.g. sending Feedback loop if MailID and original email is still available in the
_mail system_.


== Other ways calendar spam occur

=== Subscription to shared calendars

Malicious events can end up in user calendars through shared calendars.

Shared calendars are have a single origin and users are subscribed to its events,
and therefore manipulation of the calendar source will impact all its subscribers.

Popular calendars, such as official calendars (e.g. public and bank holidays),
schedules of shows and sports teams, are valuable targets for malicious actors.

Disturbingly, very often calendar applications do not allow deletion
of such shared events if the subscription is set to "`read-only`". This means
that malicious events propagated through such calendars may not even be
eligible for recipient removal, which adds salt to injury.

The only approach for users of these calendar applications are to unsubscribe
the entire calendar, even though all previous events will be deleted from
the user's calendar when unsubscribed.
More robust controls are certainly needed for calendar subscribers.


==== iTIP

Calendar systems using iTIP for direct communication between each other e.g. within
the same calendar system also need to consider and implement anti-abuse options as
mentioned above.


== Conclusion

Spam is along-standing and well-known email problem. As email is a commonly used transport
for calendar ("`meeting`") invitations and events, spammers are now using these calendar
events and invitations as a spam vector. Consequently, knowledge of both domains is
required to develop defenses against these attacks.

This document provides email and calendar system operators with an introduction to
calendar spam, and best practices for identifying and mitigating calendar spam.
Implementing these guidelines will largely be system-specific.

As the "war" against malware, including spam, is dynamic and ever-changing, email and
calendar system experts will need to share their expertise and experiences with each
other on an ongoing basis. CalConnect's collaboration with M3AAWG represents the first
formal collaboration in this area.

== Acknowledgements

The editor of this document wishes to thank the experts of CalConnect --
the Calendaring and Scheduling Consortium and attendees of the M3AAWG conference sessions
about the topic, as well as the following individuals who have participated in the
drafting, review, and discussion of this document:

Arne Allisat, Bron Gondwana, Andrew Laurence, Andrey Maevsky,
Dave Thewlis, Jesse Thompson and Ronald Tse.

Author

Thomas Schäfer (editor)

1&1 Mail&Media Development and Technology GmbH


[[AnnexA]]
[appendix,obligation=informative]
== Technical information

=== Structure of a best practice iMIP message containing an event

An email message should only contain a single iCalendar attachment (an iMIP file).

NOTE: Current practice allows attaching multiple iCalendar attachments
to a single email.

The recommended MIME/`multipart` structure of the email is provided
as follows:

* a single `multipart/mixed` part, which contains:
** a single `multipart/alternative` part, which contains:
*** a `text/plain` part; and
*** a `text/html` part;
** a `text/calendar` part with `method=REQUEST`; and
** an `application/ics` part, with a `content-disposition:attachment`, in `BASE64` encoding


This recommended structure was devised through interoperability testing with
various existing implementations.

Some clients will only see the part with the standard `text/calendar` content-type and the
method header. Other clients are only able to attached parts with `application/ics` (which
is non-standard).

It is recommended that the filename of the `application/ics` part ends
with the `.ics` file extension.

Some vendors add links within the HTML part which can be used from non-calendaring-aware
email clients to accept or decline a request without having to process the calendar parts
at all. The server just updates the ORGANIZER’s copy of the event based on the link
clicked.

When using calendar systems that conforms to calendaring standards,
the structure of the email will be like
above and the `text/plain` and `text/html` part of the message in the body will also
include information of the event e.g. subject, description, ... .

This does not prevent
spammers from not including this potential malicious content besides the attached files,
so all parts need to be parsed to detect malicious content in events.

[bibliography]
== Bibliography

* [[[ISO27000,ISO/IEC 27000:2018]]], _Information technology -- Security techniques -- Information security management systems -- Overview and vocabulary_

* [[[SMTP,IETF RFC 2821]]], _Simple Mail Transfer Protocol (SMTP)_ https://www.ietf.org/rfc/rfc2821.txt
