:repo-name: csd-calspam-bcp

= CalConnect Standard: Calendar operator practices -- Guidelines to protect against calendar abuse

This work item belongs to TC CALSPAM.

image:https://travis-ci.com/calconnect/csd-calspam-bcp.svg?branch=master["Build Status", link="https://travis-ci.com/calconnect/csd-calspam-bcp"]

This document is available in its rendered forms here:

* https://calconnect.github.io/csd-calspam-bcp/[CalConnect Calendar operator practices -- Guidelines to protect against calendar abuse (HTML)]
* https://calconnect.github.io/csd-calspam-bcp/csd-calspam-bcp.pdf[PDF]
* https://calconnect.github.io/csd-calspam-bcp/csd-calspam-bcp.xml[Metanorma XML]
* https://calconnect.github.io/csd-calspam-bcp/csd-calspam-bcp.rxl[Relaton XML (Bibliographic item)]


== Fetching the document

[source,sh]
----
git clone https://gitlab.com/calconnect/csd-calspam-bcp/
----

== Installing Build Tools

See https://www.metanorma.com/overview/getting-started/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


== Building The Document

[source,sh]
----
make clean all
----

The following outputs will be built:

* CSD XML (https://github.com/calconnect/metanorma-model-csd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)
* Word DOC (`[filename].doc`)


== Iterating the document

[source,sh]
----
make html
open csd-*.html
----

